version: "3.8"
services:
  derby:
    image: "az82/docker-derby:v1.5"
    ports:
      - "1527:1527"
  employee-service:
    image: employee-service
    build:
      context: employee-service/
    ports:
      - "8080:8080"
    depends_on:
      - derby

  employee-client:
    image: employee-client
    build:
      context: employee-client/
    ports:
      - "9090:8080"
    depends_on:
      - derby