version: "3.8"
services:
  derby:
    image: "az82/docker-derby:v1.5"
    ports:
      - "1527:1527"
  employee-event:
    image: employee-event
    build:
      context: employee-event/
    ports:
      - "8090:8080"
    depends_on:
      - derby
  employee-service:
    image: employee-service
    environment:
      - DB_NAME=sample
      - DB_USER=app
      - DB_PASSWORD=app
    build:
      context: employee-service/
    ports:
      - "8080:8080"
    depends_on:
      - derby
  employee-client:
    image: employee-client
    build:
      context: employee-client/
    ports:
      - "9090:8080"
    depends_on:
      - employee-service
      - employee-event
