version: "3.8"
services:
  derby:
    image: az82/docker-derby:v1.5
    networks:
      - backend
  flyway:
    image: flyway/flyway:7.0.1-alpine
    command: -url=jdbc:derby://derby:1527/sample;create=true -user=app -password=app -connectRetries=60 migrate
    volumes:
      - ./employee-service/flyway/sql:/flyway/sql
    depends_on:
      - derby
    networks:
      - backend
  employee-event:
    image: employee-event
    build:
      context: employee-event/
    #    ports:
    #      - "8090:8080"
    depends_on:
      - derby
    networks:
      - backend
  employee-service:
    image: employee-service
    environment:
      - DB_NAME=sample
      - DB_USER=app
      - DB_PASSWORD=app
      - DB_PORT=1527
      - DOCKER_HOST=derby
    build:
      context: employee-service/
    #    ports:
    #      - "8091:8080"
    depends_on:
      - derby
    networks:
      - backend
  employee-client:
    image: employee-client
    build:
      context: employee-client/
    ports:
      - "8080:8080"
    depends_on:
      - employee-service
      - employee-event
    networks:
      - frontend
      - backend
networks:
  backend:
  frontend: